# Generated by Django 4.2.4 on 2023-09-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_contactus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='Name',
        ),
    ]
