# Generated by Django 4.2.4 on 2023-09-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_contactus_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
