# Generated by Django 4.2.4 on 2023-09-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_category_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
